version: 2
updates:
  # Keep Python dependencies up to date (requirements.txt / pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"                  # Location of your dependency files
    schedule:
      interval: "weekly"            # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"                  # Root of repo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
