name: AI PR CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  # ----------------------------------------------------
  # 1. CI: run tests, bandit, collect metrics
  # ----------------------------------------------------
  build-test:
    runs-on: ubuntu-latest
    outputs:
      risk_score: ${{ steps.metrics.outputs.risk_score }}
      pipeline_success: ${{ steps.metrics.outputs.pipeline_success }}
      avg_build_time: ${{ steps.metrics.outputs.avg_build_time }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest bandit jq

      - name: Record start time
        id: start
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Run Pytest
        id: pytest
        continue-on-error: true
        run: |
          pytest --maxfail=1 --disable-warnings -q > pytest_results.txt
          echo "pytest_exit=$?" >> $GITHUB_ENV

      - name: Run Bandit
        id: bandit
        continue-on-error: true
        run: |
          bandit -r src > bandit_report.txt
          echo "bandit_exit=$?" >> $GITHUB_ENV

      - name: Collect Metrics
        id: metrics
        run: |
          end_time=$(date +%s)
          build_time=$((end_time - $start_time))
          build_min=$((build_time / 60))
          build_sec=$((build_time % 60))

          if [ "$pytest_exit" -eq 0 ] && [ "$bandit_exit" -eq 0 ]; then
            success=100
          elif [ "$pytest_exit" -eq 0 ] || [ "$bandit_exit" -eq 0 ]; then
            success=50
          else
            success=0
          fi

          issues=$(grep -c "Issue:" bandit_report.txt || true)
          tests_failed=$(grep -c "FAILED" pytest_results.txt || true)
          risk=$(( (issues * 5) + (tests_failed * 10) ))
          [ $risk -gt 100 ] && risk=100

          echo "risk_score=$risk" >> $GITHUB_OUTPUT
          echo "pipeline_success=$success" >> $GITHUB_OUTPUT
          echo "avg_build_time=${build_min}m${build_sec}s" >> $GITHUB_OUTPUT

  # ----------------------------------------------------
  # 2. Comment metrics on PR
  # ----------------------------------------------------
  comment-metrics:
    needs: build-test
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const risk = "${{needs.build-test.outputs.risk_score}}";
            const success = "${{needs.build-test.outputs.pipeline_success}}";
            const time = "${{needs.build-test.outputs.avg_build_time}}";
            const body = `
            ### 🚦 CI Metrics
            | Metric | Value |
            |--------|-------|
            | Risk Score | ${risk}/100 |
            | Pipeline Success | ${success}% |
            | Avg Build Time | ${time} |
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

  # ----------------------------------------------------
  # 3. AI PR Agent Review
  # ----------------------------------------------------
  pr-agent:
    needs: build-test
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    outputs:
      ai_approved: ${{ steps.set-approval.outputs.ai_approved }}
    steps:
      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide AI approval
        id: set-approval
        run: |
          if [[ "${{ needs.build-test.outputs.risk_score }}" -le 30 ]]; then
            echo "ai_approved=true" >> $GITHUB_OUTPUT
          else
            echo "ai_approved=false" >> $GITHUB_OUTPUT
          fi

  # ----------------------------------------------------
  # 4. Auto-merge if low risk
  # ----------------------------------------------------
  auto-merge:
    needs: [build-test, pr-agent]
    if: github.event_name == 'pull_request_target' && needs.pr-agent.outputs.ai_approved == 'true' && needs.build-test.outputs.pipeline_success == '100'
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ----------------------------------------------------
  # 5. Publish Dashboard JSON
  # ----------------------------------------------------
  publish-dashboard:
    needs: [build-test, pr-agent, auto-merge]
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    outputs:
      json_path: ${{ steps.make.outputs.json_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make PR JSON
        id: make
        run: |
          mkdir -p reports
          path="reports/pr_${{ github.event.pull_request.number }}.json"
          cat <<EOF > $path
          {
            "pr_number": "${{ github.event.pull_request.number }}",
            "title": "${{ github.event.pull_request.title }}",
            "risk_score": "${{ needs.build-test.outputs.risk_score }}",
            "pipeline_success": "${{ needs.build-test.outputs.pipeline_success }}",
            "avg_build_time": "${{ needs.build-test.outputs.avg_build_time }}",
            "ai_approved": "${{ needs.pr-agent.outputs.ai_approved }}"
          }
          EOF
          echo "json_path=$path" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: pr-json
          path: ${{ steps.make.outputs.json_path }}

  # ----------------------------------------------------
  # 6. Send JSON to Figma
  # ----------------------------------------------------
  send-to-figma:
    needs: publish-dashboard
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pr-json
          path: ./out

      - name: Post to Figma REST API
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE_KEY: 1430507240568862216
        run: |
          content=$(cat out/*.json | jq -Rs .)
          curl -X POST \
            -H "X-Figma-Token: $FIGMA_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.figma.com/v1/files/$FIGMA_FILE_KEY/comments" \
            -d "{\"message\": \"PR Metrics\", \"client_meta\": {}, \"comment\": $content }"

  # ----------------------------------------------------
  # 7. Deploy Pages (optional)
  # ----------------------------------------------------
  deploy-pages:
    needs: publish-dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: reports
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./reports
      - uses: actions/deploy-pages@v4
