name: Auto PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ⬇️ Download metrics artifact from CI
      - name: Download CI metrics
        uses: actions/download-artifact@v3
        with:
          name: pr-metrics
          path: ./metrics

      # Optional: show the file for debugging
      - name: Show metrics.json
        run: cat ./metrics/metrics.json || echo "No metrics.json found"

      - name: Run PR Agent
        uses: Codium-ai/pr-agent@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_path: .github/pr-agent.yml
